language: c

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1165d088c0b8da252a52
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - export SOURCE_DIR=`pwd`
  - sudo apt-get update -qq
  - sudo apt-get install -y scons git flex uuid-dev libevent-dev cmake git libzmq3-dev libgtest-dev libapr1-dev
  - cd
  - wget https://github.com/apache/qpid-proton/archive/0.10.tar.gz -O proton.tgz
  - tar xvf proton.tgz
  - cd qpid-proton*
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSYSINSTALL_BINDINGS=ON -DBUILD_JAVA=OFF -DBUILD_PERL=OFF -DBUILD_PHP=OFF -DBUILD_PYTHON=OFF -DBUILD_RUBY=OFF
  - sudo make install
  - cd
  - git clone https://github.com/OpenMAMA/OpenMAMA.git
  - cd OpenMAMA
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  - scons product=mama middleware=qpid with_unittest=y gtest_home=/usr/local
  - export MAMA_SOURCE=$(pwd)
  - export MAMA_INSTALL=$MAMA_SOURCE/$(ls -1 | grep "openmama_install_*")
  - export WOMBAT_PATH=$MAMA_SOURCE/mama/c_cpp/src/examples:$MAMA_SOURCE/mama/c_cpp/src/gunittest/c:$SOURCE_DIR/config
  - export PATH=$MAMA_INSTALL/bin:$PATH
  - export LD_LIBRARY_PATH=$MAMA_INSTALL/lib

script:
 - cd $SOURCE_DIR
 - cmake -DMAMA_ROOT=$MAMA_INSTALL -DCMAKE_INSTALL_PREFIX=$MAMA_INSTALL .
 - make install
 - UnitTestCommonC -m zmq -p qpidmsg -i Q
 - UnitTestMamaC -m zmq -p qpidmsg -i Q
 - UnitTestMamaCPP -m zmq -p qpidmsg -i Q
 - UnitTestMamaDateTimeC -m zmq -p qpidmsg -i Q
 - UnitTestMamaMiddlewareC -m zmq -p qpidmsg -i Q
 - UnitTestMamaMsgC -m zmq -p qpidmsg -i Q
 - UnitTestMamaPayloadC -m zmq -p qpidmsg -i Q
 - UnitTestMamaPriceC -m zmq -p qpidmsg -i Q
